package com.auth8.persistent.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Device was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Device extends CayenneDataObject {

    public static final String EMAIL_PROPERTY = "email";
    public static final String NAME_PROPERTY = "name";
    public static final String REGID_PROPERTY = "regid";

    public static final String ID_PK_COLUMN = "ID";

    public void setEmail(String email) {
        writeProperty(EMAIL_PROPERTY, email);
    }
    public String getEmail() {
        return (String)readProperty(EMAIL_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setRegid(String regid) {
        writeProperty(REGID_PROPERTY, regid);
    }
    public String getRegid() {
        return (String)readProperty(REGID_PROPERTY);
    }

}
