package com.auth8.persistent.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _User was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _User extends CayenneDataObject {

    public static final String PRIVATE_KEY_PROPERTY = "privateKey";
    public static final String PUBLIC_KEY_PROPERTY = "publicKey";

    public static final String ID_PK_COLUMN = "ID";

    public void setPrivateKey(String privateKey) {
        writeProperty(PRIVATE_KEY_PROPERTY, privateKey);
    }
    public String getPrivateKey() {
        return (String)readProperty(PRIVATE_KEY_PROPERTY);
    }

    public void setPublicKey(String publicKey) {
        writeProperty(PUBLIC_KEY_PROPERTY, publicKey);
    }
    public String getPublicKey() {
        return (String)readProperty(PUBLIC_KEY_PROPERTY);
    }

}
