/* Table: SEQUENCE */
CREATE TABLE PUBLIC.SEQUENCE (
    SEQ_NAME VARCHAR(50) NOT NULL,
    SEQ_COUNT DECIMAL(38)
);

ALTER TABLE PUBLIC.SEQUENCE ADD CONSTRAINT CONSTRAINT_7 PRIMARY KEY (SEQ_NAME);

INSERT INTO SEQUENCE (SEQ_NAME, SEQ_COUNT) VALUES 
    ('SEQ_GEN', 0);

/* Table: SETTING */
CREATE TABLE PUBLIC.SETTING (
    ID BIGINT(19) NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(2147483647),
    SETTING_VALUE VARCHAR(2147483647)
);

ALTER TABLE PUBLIC.SETTING ADD CONSTRAINT CONSTRAINT_A PRIMARY KEY (ID);

/* Table: SUBJECT */
CREATE TABLE PUBLIC.SUBJECT (
    ID BIGINT(19) NOT NULL AUTO_INCREMENT,
    PRIVATEKEY VARCHAR(2147483647),
    PUBLICKEY VARCHAR(2147483647)
);

ALTER TABLE PUBLIC.SUBJECT ADD CONSTRAINT CONSTRAINT_B PRIMARY KEY (ID);
