CREATE TABLE PUBLIC.SETTING (ID BIGINT NOT NULL AUTO_INCREMENT, NAME VARCHAR(2147483647) NULL, SETTING_VALUE VARCHAR(2147483647) NULL, PRIMARY KEY (ID))
;

CREATE TABLE PUBLIC.SUBJECT (ID BIGINT NOT NULL AUTO_INCREMENT, PRIVATEKEY VARCHAR(2147483647) NULL, PUBLICKEY VARCHAR(2147483647) NULL, PRIMARY KEY (ID))
;

CREATE TABLE PUBLIC.DEVICE (EMAIL VARCHAR(100) NOT NULL, ID BIGINT NOT NULL AUTO_INCREMENT, NAME VARCHAR(100) NULL, REGID VARCHAR(500) NOT NULL, PRIMARY KEY (ID))
;

CREATE TABLE AUTO_PK_SUPPORT (  TABLE_NAME CHAR(100) NOT NULL,  NEXT_ID BIGINT NOT NULL,  PRIMARY KEY(TABLE_NAME))
;

DELETE FROM AUTO_PK_SUPPORT WHERE TABLE_NAME IN ('DEVICE', 'SETTING', 'SUBJECT')
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('DEVICE', 200)
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('SETTING', 200)
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('SUBJECT', 200)
;

